// const product = [
//   {
//     id: 1,
//     title: "Amazon Basics Electric Egg Boiler",
//     desc: "3 Boiling Modes | Automatic Operation | Overheat Protection",
//     price: 999,
//     originalPrice: 1499,
//     discount: "33% off",
//     rating: 4.2,
//     img: "https://rukminim2.flixcart.com/image/850/1000/xif0q/egg-cooker/j/v/z/8-2-in1-egg-boiler-and-poacher-500-watt-silver-grey-boil-8-eggs-original-imaghqtftj9jwdev.jpeg?q=20&crop=false",
//     category: "kitchen",
//   },
//   {
//     id: 2,
//     title: "Prestige Electric Kettle",
//     desc: "1.5 Liter Capacity | Stainless Steel | 1500 Watts | Cordless",
//     price: 1095,
//     originalPrice: 1499,
//     discount: "27% off",
//     rating: 4.5,
//     img: "https://m.media-amazon.com/images/I/71PeGhl9sqL.jpg",
//     category: "kitchen",
//   },
//   {
//     id: 3,
//     title: "Bajaj Majesty Hand Mixer",
//     desc: "350 Watts | 2 Speed Control | 2 Stainless Steel Beaters",
//     price: 1299,
//     originalPrice: 1990,
//     discount: "35% off",
//     rating: 4.0,
//     img: "https://m.media-amazon.com/images/I/61uQ+GRiMTL._AC_UF894,1000_QL80_.jpg",
//     category: "kitchen",
//   },
//   {
//     id: 4,
//     title: "Butterfly Smart Glass Top Gas Stove",
//     desc: "2 Burner | Brass Burners | Auto Ignition | Black",
//     price: 3499,
//     originalPrice: 4999,
//     discount: "30% off",
//     rating: 4.3,
//     img: "https://m.media-amazon.com/images/I/71nQPcpcNbL._AC_UF894,1000_QL80_.jpg",
//     category: "kitchen",
//   },
//   {
//     id: 5,
//     title: "Morphy Richards Food Processor",
//     desc: "1600 Watts | 1.75L Jar | 3 Speed Control | White",
//     price: 3999,
//     originalPrice: 5999,
//     discount: "33% off",
//     rating: 4.1,
//     img: "https://5.imimg.com/data5/ECOM/Default/2023/2/QT/SK/ZO/5593817/1-1327fa6a-3bbf-4b8b-b360-69fe94ce7010.jpg",
//     category: "kitchen",
//   },
//   {
//     id: 6,
//     title: "Pigeon Sandwich Maker",
//     desc: "750 Watts | Non-Stick Coating | Indicator Light | Black",
//     price: 795,
//     originalPrice: 1295,
//     discount: "39% off",
//     rating: 4.0,
//     img: "https://timbuktu80.com/share-product-image/l4453-tjpgsm10003-pigeon-press-griller-s.jpg",
//     category: "kitchen",
//   },
//   {
//     id: 7,
//     title: "Borosil Microwave Oven",
//     desc: "42 Liter | 900 Watts | 10 Power Levels | Black",
//     price: 8999,
//     originalPrice: 12999,
//     discount: "31% off",
//     rating: 4.2,
//     img: "https://rukminid2.flixcart.com/image/850/1000/kw3v0cw0/otg-new/l/j/v/-original-imag8ut7ptctzwnx.jpeg?q=90&crop=false",
//     category: "kitchen",
//   },
//   {
//     id: 8,
//     title: "Havells Induction Cooktop",
//     desc: "2000 Watts | 7 Cooking Presets | Auto Pan Detection",
//     price: 2199,
//     originalPrice: 2999,
//     discount: "27% off",
//     rating: 4.4,
//     img: "https://www.hindustantimes.com/ht-img/img/2024/02/27/550x309/best_induction_stove_1709038407290_1709038423806.jpg",
//     category: "kitchen",
//   },
//   {
//     id: 9,
//     title: "Inalsa Electric Rice Cooker",
//     desc: "1.8 Liter | 650 Watts | Non-Stick Inner Pot | White",
//     price: 1499,
//     originalPrice: 1999,
//     discount: "25% off",
//     rating: 3.9,
//     img: "https://ankurelectricals.com/cdn/shop/files/1_579c6bb1-e5e8-4cce-a582-9fa2aec10fdb.png?v=1730358818",
//     category: "kitchen",
//   },
//   {
//     id: 10,
//     title: "Philips Juicer",
//     desc: "500 Watts | 1.5L Jug | 2 Speed Settings | White",
//     price: 1999,
//     originalPrice: 2499,
//     discount: "20% off",
//     rating: 4.1,
//     img: "https://cdn.anscommerce.com/live/image/catalog/brandstore/philips/HL7580Feature_Powerfulmotor_460x330pxls.jpg",
//     category: "kitchen",
//   },
//   {
//     id: 11,
//     title: "Prestige Mixer Grinder",
//     desc: "750 Watts | 3 Jars | Stainless Steel Blades | Purple",
//     price: 2499,
//     originalPrice: 3499,
//     discount: "29% off",
//     rating: 4.3,
//     img: "https://m.media-amazon.com/images/I/51ZykaL8q6L._AC_UF894,1000_QL80_.jpg",
//     category: "kitchen",
//   },
//   {
//     id: 12,
//     title: "Bajaj Rex Mixer Grinder",
//     desc: "500 Watts | 3 Jars | Stainless Steel Blades | White",
//     price: 1799,
//     originalPrice: 2499,
//     discount: "28% off",
//     rating: 4.0,
//     img: "https://m.media-amazon.com/images/I/51ZykaL8q6L._AC_UF894,1000_QL80_.jpg",
//     category: "kitchen",
//   },
//   {
//     id: 13,
//     title: "Kent Hand Blender",
//     desc: "150 Watts | 2 Speed Control | Stainless Steel Blades",
//     price: 1499,
//     originalPrice: 1999,
//     discount: "25% off",
//     rating: 3.8,
//     img: "https://5.imimg.com/data5/ANDROID/Default/2024/10/457939575/CJ/QU/VN/92037128/product-jpeg-500x500.jpg",
//     category: "kitchen",
//   },
//   {
//     id: 14,
//     title: "Usha Induction Cooktop",
//     desc: "2000 Watts | 7 Cooking Presets | Auto Pan Detection",
//     price: 2099,
//     originalPrice: 2799,
//     discount: "25% off",
//     rating: 4.2,
//     img: "https://images.jdmagicbox.com/quickquotes/images_main/usha-cook-joy-3820-2000-watt-induction-cooktop-with-touch-black-178182875-gjg45.jpg",
//     category: "kitchen",
//   },
//   {
//     id: 15,
//     title: "Pigeon Electric Kettle",
//     desc: "1.5 Liter | 1500 Watts | Stainless Steel | Black",
//     price: 999,
//     originalPrice: 1499,
//     discount: "33% off",
//     rating: 4.1,
//     img: "https://rukminim2.flixcart.com/image/850/1000/xif0q/electric-kettle/t/p/1/kessel-3in1-value-pack-kessel-3in1-value-pack-pigeon-original-imags4yn9z5ubh4a.jpeg?q=20&crop=false",
//     category: "kitchen",
//   },
//   {
//     id: 16,
//     title: "Borosil Microwave Oven",
//     desc: "20 Liter | 700 Watts | 5 Power Levels | White",
//     price: 5999,
//     originalPrice: 7999,
//     discount: "25% off",
//     rating: 4.0,
//     img: "https://img.tatacliq.com/images/i19//437Wx649H/MP000000023240938_437Wx649H_202408091943401.jpeg",
//     category: "kitchen",
//   },
//   {
//     id: 17,
//     title: "Prestige Wet Grinder",
//     desc: "200 Watts | 2 Liter Capacity | Stainless Steel Drum",
//     price: 5999,
//     originalPrice: 7999,
//     discount: "25% off",
//     rating: 4.3,
//     img: "https://dukaan.b-cdn.net/700x700/webp/4112024/67eeb815-ae3c-4622-9dcd-882aed91b3eb/1-849be5e1-124d-47e1-a790-b59a6779d3cc.jpeg",
//     category: "kitchen",
//   },
//   {
//     id: 18,
//     title: "Butterfly Air Fryer",
//     desc: "3 Liter | 1500 Watts | Digital Display | Black",
//     price: 4999,
//     originalPrice: 6999,
//     discount: "29% off",
//     rating: 4.1,
//     img: "https://m.media-amazon.com/images/I/514+jUGdT4L._AC_UF1000,1000_QL80_.jpg",
//     category: "kitchen",
//   },
//   {
//     id: 19,
//     title: "Morphy Richards Hand Mixer",
//     desc: "300 Watts | 5 Speed Control | Stainless Steel Beaters",
//     price: 1499,
//     originalPrice: 1999,
//     discount: "25% off",
//     rating: 3.9,
//     img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT-befwH1fnuDpx75EULfE2ZuJWIVGsjd04gw&s",
//     category: "kitchen",
//   },
//   {
//     id: 20,
//     title: "Inalsa Juicer Mixer Grinder",
//     desc: "1000 Watts | 3 Jars | Stainless Steel Blades | Black",
//     price: 2999,
//     originalPrice: 3999,
//     discount: "25% off",
//     rating: 4.2,
//     img: "https://m.media-amazon.com/images/I/61Xlrm+1LZL._AC_UF894,1000_QL80_.jpg",
//     category: "kitchen",
//   },
//   {
//     id: 21,
//     title: "Philips Air Fryer",
//     desc: "4.1 Liter | 1400 Watts | Digital Display | Black",
//     price: 7999,
//     originalPrice: 9999,
//     discount: "20% off",
//     rating: 4.5,
//     img: "https://www.u-buy.com.ng/productimg/?image=aHR0cHM6Ly9pbWFnZXMtbmEuc3NsLWltYWdlcy1hbWF6b24uY29tL2ltYWdlcy9JLzUxaUI3SkZsUm5MLmpwZw.jpg",
//     category: "kitchen",
//   },
//   {
//     id: 22,
//     title: "Butterfly Rice Cooker",
//     desc: "1.8 Liter | 650 Watts | Non-Stick Inner Pot | White",
//     price: 1599,
//     originalPrice: 2199,
//     discount: "27% off",
//     rating: 4.0,
//     img: "https://homedecorlo.com/cdn/shop/products/41FO5hwzy2L.jpg?v=1624673229",
//     category: "kitchen",
//   },
//   {
//     id: 23,
//     title: "Prestige Pressure Cooker",
//     desc: "3 Liter | Stainless Steel | Induction Base | Silver",
//     price: 1299,
//     originalPrice: 1799,
//     discount: "28% off",
//     rating: 4.4,
//     img: "https://shop.ttkprestige.com/media/catalog/product/1/6/1681-20334-P-IMG1.jpg",
//     category: "kitchen",
//   },
//   {
//     id: 24,
//     title: "Borosil Glass Dinner Set",
//     desc: "35 Pieces | Microwave Safe | Transparent",
//     price: 2499,
//     originalPrice: 3499,
//     discount: "29% off",
//     rating: 4.3,
//     img: "https://homeplus.in/wp-content/uploads/2022/12/61Owv-SU27L._SL1500_.webp",
//     category: "kitchen",
//   },
//   {
//     id: 25,
//     title: "Milton Thermosteel Flask",
//     desc: "1 Liter | Stainless Steel | Vacuum Insulated | Silver",
//     price: 899,
//     originalPrice: 1299,
//     discount: "31% off",
//     rating: 4.2,
//     img: "https://5.imimg.com/data5/SELLER/Default/2024/3/399452154/UW/OZ/NR/76841865/3-5-ltr-milton-thermosteel-flask-500x500.jpg",
//     category: "kitchen",
//   },
//   {
//     id: 26,
//     title: "Cello Plastic Storage Containers",
//     desc: "Set of 5 | Airtight Lids | Microwave Safe | Assorted Colors",
//     price: 599,
//     originalPrice: 899,
//     discount: "33% off",
//     rating: 4.0,
//     img: "https://img.tatacliq.com/images/i19//437Wx649H/MP000000023284640_437Wx649H_202408111030091.jpeg",
//     category: "kitchen",
//   },
//   {
//     id: 27,
//     title: "Nova Stainless Steel Cookware Set",
//     desc: "7 Pieces | Induction Bottom | Silver",
//     price: 2999,
//     originalPrice: 3999,
//     discount: "25% off",
//     rating: 4.1,
//     img: "https://www.emergencyzone.com/cdn/shop/products/cookset_0019_3232p_1200x1200.jpg?v=1615574588",
//     category: "kitchen",
//   },
//   {
//     id: 28,
//     title: "Wonderchef Non-Stick Kadai",
//     desc: "2 Liter | Granite Coating | Induction Base | Black",
//     price: 1099,
//     originalPrice: 1599,
//     discount: "31% off",
//     rating: 4.3,
//     img: "https://www.wonderchef.com/cdn/shop/files/6802994.jpg?v=1745670368",
//     category: "kitchen",
//   },
//   {
//     id: 29,
//     title: "Pigeon Chopping Board",
//     desc: "Plastic | BPA Free | Non-Slip Base | Green",
//     price: 199,
//     originalPrice: 299,
//     discount: "33% off",
//     rating: 3.9,
//     img: "https://m.media-amazon.com/images/I/61Zb6YnFNqL.jpg",
//     category: "kitchen",
//   },
//   {
//     id: 30,
//     title: "Borosil Glass Mixing Bowls",
//     desc: "Set of 3 | Microwave Safe | Transparent",
//     price: 699,
//     originalPrice: 999,
//     discount: "30% off",
//     rating: 4.2,
//     img: "https://rukminim2.flixcart.com/image/850/1000/xif0q/bowl/l/w/0/4-cect-gbowl-setof4-2100ml-withlid-cutting-edge-original-imah4kfu2kzq4nwd.jpeg?q=20&crop=false",
//     category: "kitchen",
//   },
//   {
//     id: 31,
//     title: "Milton Thermosteel Lunch Box",
//     desc: "3 Compartment | 1.2 Liter | Stainless Steel | Silver",
//     price: 799,
//     originalPrice: 1199,
//     discount: "33% off",
//     rating: 4.1,
//     img: "https://m.media-amazon.com/images/I/51i16sIlF7L._AC_UF894,1000_QL80_.jpg",
//     category: "kitchen",
//   },
//   {
//     id: 32,
//     title: "Prestige Tawa",
//     desc: "Non-Stick | Induction Base | 27 cm | Black",
//     price: 499,
//     originalPrice: 799,
//     discount: "38% off",
//     rating: 4.0,
//     img: "https://judge.ttkprestige.com/media/catalog/product/7/5/7524-37277-P-IMG1.jpg",
//     category: "kitchen",
//   },
//   {
//     id: 33,
//     title: "Borosil Glass Water Bottle",
//     desc: "1 Liter | Leak Proof | BPA Free | Transparent",
//     price: 399,
//     originalPrice: 599,
//     discount: "33% off",
//     rating: 4.2,
//     img: "https://myborosil.com/cdn/shop/files/my-borosil-borosilicate-glass-bottles-750-ml-x-3-crysto-glass-bottle-set-of-3-blue-lid-32349054206090.jpg",
//     category: "kitchen",
//   },
//   {
//     id: 34,
//     title: "Cello Plastic Water Jug",
//     desc: "2 Liter | BPA Free | Transparent",
//     price: 149,
//     originalPrice: 249,
//     discount: "40% off",
//     rating: 3.8,
//     img: "https://m.media-amazon.com/images/I/61Z3BEj+c9L._AC_UF350,350_QL80_.jpg",
//     category: "kitchen",
//   },
//   {
//     id: 35,
//     title: "Nova Stainless Steel Spoon Set",
//     desc: "Set of 6 | Mirror Finish | Silver",
//     price: 299,
//     originalPrice: 499,
//     discount: "40% off",
//     rating: 4.0,
//     img: "https://m.media-amazon.com/images/I/81tXKPh4j2L._AC_UF350,350_QL80_.jpg",
//     category: "kitchen",
//   },
//   {
//     id: 36,
//     title: "Wonderchef Kitchen Knife Set",
//     desc: "Set of 3 | Stainless Steel | Black Handle",
//     price: 899,
//     originalPrice: 1299,
//     discount: "31% off",
//     rating: 4.3,
//     img: "https://m.media-amazon.com/images/I/81VRmyhZKNS._AC_UF350,350_QL80_.jpg",
//     category: "kitchen",
//   },
//   {
//     id: 37,
//     title: "Pigeon Kitchen Scissors",
//     desc: "Stainless Steel | Multipurpose | Black",
//     price: 199,
//     originalPrice: 299,
//     discount: "33% off",
//     rating: 3.9,
//     img: "https://m.media-amazon.com/images/I/81RQVwpmK7L._AC_UF350,350_QL80_.jpg",
//     category: "kitchen",
//   },
//   {
//     id: 38,
//     title: "Borosil Glass Measuring Cup",
//     desc: "500 ml | Microwave Safe | Transparent",
//     price: 249,
//     originalPrice: 399,
//     discount: "38% off",
//     rating: 4.1,
//     img: "https://i5.walmartimages.com/asr/bebba757-2bc2-4588-a5d8-db9adc8d48a6.4ec35d10a101940a73a22aacf9df8f36.jpeg?odnHeight=768&odnWidth=768&odnBg=FFFFFF",
//     category: "kitchen",
//   },
//   {
//     id: 39,
//     title: "Milton Thermosteel Sipper",
//     desc: "600 ml | Stainless Steel | Vacuum Insulated | Silver",
//     price: 599,
//     originalPrice: 899,
//     discount: "33% off",
//     rating: 4.2,
//     img: "https://cdn.zeptonow.com/production/ik-seo/tr:w-640,ar-1200-1200,pr-true,f-auto,q-80/cms/product_variant/46c82fea-fb0e-47d7-b4cd-f9cd2b6553ba/Milton-Flip-Lid-Thermosteel-Water-Bottle-1-L.jpeg",
//     category: "kitchen",
//   },
//   {
//     id: 40,
//     title: "Prestige Spatula Set",
//     desc: "Set of 3 | Silicone Head | Wooden Handle",
//     price: 299,
//     originalPrice: 499,
//     discount: "40% off",
//     rating: 4.0,
//     img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRaH42-3mlBJY9d8TfQG_ehohnkaFmLBdcRjw&s",
//     category: "kitchen",
//   },
//   {
//     id: 41,
//     title: "Borosil Glass Storage Box",
//     desc: "1 Liter | Airtight Lid | Microwave Safe | Transparent",
//     price: 349,
//     originalPrice: 499,
//     discount: "30% off",
//     rating: 4.1,
//     img: "https://5.imimg.com/data5/SELLER/Default/2024/9/452728853/HU/ZO/FI/141467672/borosil-round-320-ml-lunch-box-set-of-3-500x500.jpg",
//     category: "kitchen",
//   },
//   {
//     id: 42,
//     title: "Cello Plastic Storage Jars",
//     desc: "Set of 3 | Airtight Lids | Assorted Colors",
//     price: 499,
//     originalPrice: 799,
//     discount: "38% off",
//     rating: 3.9,
//     img: "https://m.media-amazon.com/images/I/71xJlektz3L._AC_UF894,1000_QL80_.jpg",
//     category: "kitchen",
//   },
//   {
//     id: 43,
//     title: "Nova Stainless Steel Tongs",
//     desc: "12 Inch | Silicone Tips | Silver",
//     price: 199,
//     originalPrice: 299,
//     discount: "33% off",
//     rating: 4.0,
//     img: "https://m.media-amazon.com/images/I/716l-yNe7cL.jpg",
//     category: "kitchen",
//   },
//   {
//     id: 44,
//     title: "Wonderchef Rolling Pin",
//     desc: "Wooden | 14 Inch | Traditional Design",
//     price: 249,
//     originalPrice: 399,
//     discount: "38% off",
//     rating: 4.1,
//     img: "https://rukminim2.flixcart.com/image/850/1000/kq18n0w0/kitchen-timer/z/3/6/ce01-canwood-original-imag44ws23k2b8pg.jpeg?q=90&crop=false",
//     category: "kitchen",
//   },
//   {
//     id: 45,
//     title: "Pigeon Kitchen Scale",
//     desc: "Digital | 5 kg Capacity | LCD Display | White",
//     price: 599,
//     originalPrice: 899,
//     discount: "33% off",
//     rating: 4.2,
//     img: "https://assets.indiadesire.com/images/PigeonAmaze1800WattInductionCooktop_indiadesire.jpg",
//     category: "kitchen",
//   },
//   {
//     id: 46,
//     title: "Borosil Glass Tea Cup",
//     desc: "300 ml | Microwave Safe | Transparent",
//     price: 149,
//     originalPrice: 249,
//     discount: "40% off",
//     rating: 4.0,
//     img: "https://www.zwende.com/cdn/shop/files/81_3ea601e6-3651-4aab-b410-d0fe65de72f5.jpg?v=1698763156&width=1080",
//     category: "kitchen",
//   },
//   {
//     id: 47,
//     title: "Milton Thermosteel Coffee Mug",
//     desc: "350 ml | Stainless Steel | Vacuum Insulated | Silver",
//     price: 499,
//     originalPrice: 799,
//     discount: "38% off",
//     rating: 4.3,
//     img: "https://rukminim2.flixcart.com/image/850/1000/l4yi7bk0/mug/s/w/y/thermosteel-coffee-mug-300-ml-silver-hot-cold-flask-soup-flask-original-imagfqgegkpcnvuf.jpeg?q=90&crop=false",
//     category: "kitchen",
//   },
//   {
//     id: 48,
//     title: "Prestige Kitchen Timer",
//     desc: "Digital | Magnetic Back | Count Up/Down | Black",
//     price: 299,
//     originalPrice: 499,
//     discount: "40% off",
//     rating: 3.9,
//     img: "https://images-eu.ssl-images-amazon.com/images/I/71xPmqaYvsL._AC_UL210_SR210,210_.jpg",
//     category: "kitchen",
//   },
//   {
//     id: 49,
//     title: "Borosil Glass Baking Dish",
//     desc: "2 Liter | Microwave Safe | Oven Safe | Transparent",
//     price: 599,
//     originalPrice: 899,
//     discount: "33% off",
//     rating: 4.1,
//     img: "https://www.bigbasket.com/media/uploads/p/l/40239838_2-femora-borosilicate-glass-baking-dish-temperature-resistant-for-baking-serving-storing-use.jpg",
//     category: "kitchen",
//   },
//   {
//     id: 50,
//     title: "Cello Plastic Chopping Board",
//     desc: "Set of 2 | BPA Free | Non-Slip Base | Green & Red",
//     price: 249,
//     originalPrice: 399,
//     discount: "38% off",
//     rating: 4.0,
//     img: "https://5.imimg.com/data5/JL/VL/HH/SELLER-4260965/pari-500x500.png",
//     category: "kitchen",
//   },
// ];

// src/Componemt/Home/Shop_by_Category/dataproducts.js

const dataproducts = [
  {
    id: 1,
    title: "Amazon Basics Electric Egg Boiler",
    desc: "3 Boiling Modes | Automatic Operation | Overheat Protection",
    price: 999,
    originalPrice: 1499,
    discount: "33% off",
    rating: 4.2,
    img: "https://rukminim2.flixcart.com/image/850/1000/xif0q/egg-cooker/j/v/z/8-2-in1-egg-boiler-and-poacher-500-watt-silver-grey-boil-8-eggs-original-imaghqtftj9jwdev.jpeg?q=20&crop=false",
    category: "kitchen",
  },
  {
    id: 2,
    title: "Prestige Electric Kettle",
    desc: "1.5 Liter Capacity | Stainless Steel | 1500 Watts | Cordless",
    price: 1095,
    originalPrice: 1499,
    discount: "27% off",
    rating: 4.5,
    img: "https://m.media-amazon.com/images/I/71PeGhl9sqL.jpg",
    category: "kitchen",
  },

  {
    id: 1,
    title: "Amazon Basics Electric Egg Boiler",
    desc: "3 Boiling Modes | Automatic Operation | Overheat Protection",
    price: 999,
    originalPrice: 1499,
    discount: "33% off",
    rating: 4.2,
    img: "https://rukminim2.flixcart.com/image/850/1000/xif0q/egg-cooker/j/v/z/8-2-in1-egg-boiler-and-poacher-500-watt-silver-grey-boil-8-eggs-original-imaghqtftj9jwdev.jpeg?q=20&crop=false",
    category: "kitchen",
  },
  {
    id: 2,
    title: "Prestige Electric Kettle",
    desc: "1.5 Liter Capacity | Stainless Steel | 1500 Watts | Cordless",
    price: 1095,
    originalPrice: 1499,
    discount: "27% off",
    rating: 4.5,
    img: "https://m.media-amazon.com/images/I/71PeGhl9sqL.jpg",
    category: "kitchen",
  },
  {
    id: 3,
    title: "Bajaj Majesty Hand Mixer",
    desc: "350 Watts | 2 Speed Control | 2 Stainless Steel Beaters",
    price: 1299,
    originalPrice: 1990,
    discount: "35% off",
    rating: 4.0,
    img: "https://m.media-amazon.com/images/I/61uQ+GRiMTL._AC_UF894,1000_QL80_.jpg",
    category: "kitchen",
  },
  {
    id: 4,
    title: "Butterfly Smart Glass Top Gas Stove",
    desc: "2 Burner | Brass Burners | Auto Ignition | Black",
    price: 3499,
    originalPrice: 4999,
    discount: "30% off",
    rating: 4.3,
    img: "https://m.media-amazon.com/images/I/71nQPcpcNbL._AC_UF894,1000_QL80_.jpg",
    category: "kitchen",
  },
  {
    id: 5,
    title: "Morphy Richards Food Processor",
    desc: "1600 Watts | 1.75L Jar | 3 Speed Control | White",
    price: 3999,
    originalPrice: 5999,
    discount: "33% off",
    rating: 4.1,
    img: "https://5.imimg.com/data5/ECOM/Default/2023/2/QT/SK/ZO/5593817/1-1327fa6a-3bbf-4b8b-b360-69fe94ce7010.jpg",
    category: "kitchen",
  },
  {
    id: 6,
    title: "Pigeon Sandwich Maker",
    desc: "750 Watts | Non-Stick Coating | Indicator Light | Black",
    price: 795,
    originalPrice: 1295,
    discount: "39% off",
    rating: 4.0,
    img: "https://timbuktu80.com/share-product-image/l4453-tjpgsm10003-pigeon-press-griller-s.jpg",
    category: "kitchen",
  },
  {
    id: 7,
    title: "Borosil Microwave Oven",
    desc: "42 Liter | 900 Watts | 10 Power Levels | Black",
    price: 8999,
    originalPrice: 12999,
    discount: "31% off",
    rating: 4.2,
    img: "https://rukminid2.flixcart.com/image/850/1000/kw3v0cw0/otg-new/l/j/v/-original-imag8ut7ptctzwnx.jpeg?q=90&crop=false",
    category: "kitchen",
  },
  {
    id: 8,
    title: "Havells Induction Cooktop",
    desc: "2000 Watts | 7 Cooking Presets | Auto Pan Detection",
    price: 2199,
    originalPrice: 2999,
    discount: "27% off",
    rating: 4.4,
    img: "https://www.hindustantimes.com/ht-img/img/2024/02/27/550x309/best_induction_stove_1709038407290_1709038423806.jpg",
    category: "kitchen",
  },
  {
    id: 9,
    title: "Inalsa Electric Rice Cooker",
    desc: "1.8 Liter | 650 Watts | Non-Stick Inner Pot | White",
    price: 1499,
    originalPrice: 1999,
    discount: "25% off",
    rating: 3.9,
    img: "https://ankurelectricals.com/cdn/shop/files/1_579c6bb1-e5e8-4cce-a582-9fa2aec10fdb.png?v=1730358818",
    category: "kitchen",
  },
  {
    id: 10,
    title: "Philips Juicer",
    desc: "500 Watts | 1.5L Jug | 2 Speed Settings | White",
    price: 1999,
    originalPrice: 2499,
    discount: "20% off",
    rating: 4.1,
    img: "https://cdn.anscommerce.com/live/image/catalog/brandstore/philips/HL7580Feature_Powerfulmotor_460x330pxls.jpg",
    category: "kitchen",
  },
  {
    id: 11,
    title: "Prestige Mixer Grinder",
    desc: "750 Watts | 3 Jars | Stainless Steel Blades | Purple",
    price: 2499,
    originalPrice: 3499,
    discount: "29% off",
    rating: 4.3,
    img: "https://m.media-amazon.com/images/I/51ZykaL8q6L._AC_UF894,1000_QL80_.jpg",
    category: "kitchen",
  },
  {
    id: 12,
    title: "Bajaj Rex Mixer Grinder",
    desc: "500 Watts | 3 Jars | Stainless Steel Blades | White",
    price: 1799,
    originalPrice: 2499,
    discount: "28% off",
    rating: 4.0,
    img: "https://m.media-amazon.com/images/I/51ZykaL8q6L._AC_UF894,1000_QL80_.jpg",
    category: "kitchen",
  },
  {
    id: 13,
    title: "Kent Hand Blender",
    desc: "150 Watts | 2 Speed Control | Stainless Steel Blades",
    price: 1499,
    originalPrice: 1999,
    discount: "25% off",
    rating: 3.8,
    img: "https://5.imimg.com/data5/ANDROID/Default/2024/10/457939575/CJ/QU/VN/92037128/product-jpeg-500x500.jpg",
    category: "kitchen",
  },
  {
    id: 14,
    title: "Usha Induction Cooktop",
    desc: "2000 Watts | 7 Cooking Presets | Auto Pan Detection",
    price: 2099,
    originalPrice: 2799,
    discount: "25% off",
    rating: 4.2,
    img: "https://images.jdmagicbox.com/quickquotes/images_main/usha-cook-joy-3820-2000-watt-induction-cooktop-with-touch-black-178182875-gjg45.jpg",
    category: "kitchen",
  },
  {
    id: 15,
    title: "Pigeon Electric Kettle",
    desc: "1.5 Liter | 1500 Watts | Stainless Steel | Black",
    price: 999,
    originalPrice: 1499,
    discount: "33% off",
    rating: 4.1,
    img: "https://rukminim2.flixcart.com/image/850/1000/xif0q/electric-kettle/t/p/1/kessel-3in1-value-pack-kessel-3in1-value-pack-pigeon-original-imags4yn9z5ubh4a.jpeg?q=20&crop=false",
    category: "kitchen",
  },
  {
    id: 16,
    title: "Borosil Microwave Oven",
    desc: "20 Liter | 700 Watts | 5 Power Levels | White",
    price: 5999,
    originalPrice: 7999,
    discount: "25% off",
    rating: 4.0,
    img: "https://img.tatacliq.com/images/i19//437Wx649H/MP000000023240938_437Wx649H_202408091943401.jpeg",
    category: "kitchen",
  },
  {
    id: 17,
    title: "Prestige Wet Grinder",
    desc: "200 Watts | 2 Liter Capacity | Stainless Steel Drum",
    price: 5999,
    originalPrice: 7999,
    discount: "25% off",
    rating: 4.3,
    img: "https://dukaan.b-cdn.net/700x700/webp/4112024/67eeb815-ae3c-4622-9dcd-882aed91b3eb/1-849be5e1-124d-47e1-a790-b59a6779d3cc.jpeg",
    category: "kitchen",
  },
  {
    id: 18,
    title: "Butterfly Air Fryer",
    desc: "3 Liter | 1500 Watts | Digital Display | Black",
    price: 4999,
    originalPrice: 6999,
    discount: "29% off",
    rating: 4.1,
    img: "https://m.media-amazon.com/images/I/514+jUGdT4L._AC_UF1000,1000_QL80_.jpg",
    category: "kitchen",
  },
  {
    id: 19,
    title: "Morphy Richards Hand Mixer",
    desc: "300 Watts | 5 Speed Control | Stainless Steel Beaters",
    price: 1499,
    originalPrice: 1999,
    discount: "25% off",
    rating: 3.9,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT-befwH1fnuDpx75EULfE2ZuJWIVGsjd04gw&s",
    category: "kitchen",
  },
  {
    id: 20,
    title: "Inalsa Juicer Mixer Grinder",
    desc: "1000 Watts | 3 Jars | Stainless Steel Blades | Black",
    price: 2999,
    originalPrice: 3999,
    discount: "25% off",
    rating: 4.2,
    img: "https://m.media-amazon.com/images/I/61Xlrm+1LZL._AC_UF894,1000_QL80_.jpg",
    category: "kitchen",
  },
  {
    id: 21,
    title: "Philips Air Fryer",
    desc: "4.1 Liter | 1400 Watts | Digital Display | Black",
    price: 7999,
    originalPrice: 9999,
    discount: "20% off",
    rating: 4.5,
    img: "https://www.u-buy.com.ng/productimg/?image=aHR0cHM6Ly9pbWFnZXMtbmEuc3NsLWltYWdlcy1hbWF6b24uY29tL2ltYWdlcy9JLzUxaUI3SkZsUm5MLmpwZw.jpg",
    category: "kitchen",
  },
  {
    id: 22,
    title: "Butterfly Rice Cooker",
    desc: "1.8 Liter | 650 Watts | Non-Stick Inner Pot | White",
    price: 1599,
    originalPrice: 2199,
    discount: "27% off",
    rating: 4.0,
    img: "https://homedecorlo.com/cdn/shop/products/41FO5hwzy2L.jpg?v=1624673229",
    category: "kitchen",
  },
  {
    id: 23,
    title: "Prestige Pressure Cooker",
    desc: "3 Liter | Stainless Steel | Induction Base | Silver",
    price: 1299,
    originalPrice: 1799,
    discount: "28% off",
    rating: 4.4,
    img: "https://shop.ttkprestige.com/media/catalog/product/1/6/1681-20334-P-IMG1.jpg",
    category: "kitchen",
  },
  {
    id: 24,
    title: "Borosil Glass Dinner Set",
    desc: "35 Pieces | Microwave Safe | Transparent",
    price: 2499,
    originalPrice: 3499,
    discount: "29% off",
    rating: 4.3,
    img: "https://homeplus.in/wp-content/uploads/2022/12/61Owv-SU27L._SL1500_.webp",
    category: "kitchen",
  },
  {
    id: 25,
    title: "Milton Thermosteel Flask",
    desc: "1 Liter | Stainless Steel | Vacuum Insulated | Silver",
    price: 899,
    originalPrice: 1299,
    discount: "31% off",
    rating: 4.2,
    img: "https://5.imimg.com/data5/SELLER/Default/2024/3/399452154/UW/OZ/NR/76841865/3-5-ltr-milton-thermosteel-flask-500x500.jpg",
    category: "kitchen",
  },
  {
    id: 26,
    title: "Cello Plastic Storage Containers",
    desc: "Set of 5 | Airtight Lids | Microwave Safe | Assorted Colors",
    price: 599,
    originalPrice: 899,
    discount: "33% off",
    rating: 4.0,
    img: "https://img.tatacliq.com/images/i19//437Wx649H/MP000000023284640_437Wx649H_202408111030091.jpeg",
    category: "kitchen",
  },
  {
    id: 27,
    title: "Nova Stainless Steel Cookware Set",
    desc: "7 Pieces | Induction Bottom | Silver",
    price: 2999,
    originalPrice: 3999,
    discount: "25% off",
    rating: 4.1,
    img: "https://www.emergencyzone.com/cdn/shop/products/cookset_0019_3232p_1200x1200.jpg?v=1615574588",
    category: "kitchen",
  },
  {
    id: 28,
    title: "Wonderchef Non-Stick Kadai",
    desc: "2 Liter | Granite Coating | Induction Base | Black",
    price: 1099,
    originalPrice: 1599,
    discount: "31% off",
    rating: 4.3,
    img: "https://www.wonderchef.com/cdn/shop/files/6802994.jpg?v=1745670368",
    category: "kitchen",
  },
  {
    id: 29,
    title: "Pigeon Chopping Board",
    desc: "Plastic | BPA Free | Non-Slip Base | Green",
    price: 199,
    originalPrice: 299,
    discount: "33% off",
    rating: 3.9,
    img: "https://m.media-amazon.com/images/I/61Zb6YnFNqL.jpg",
    category: "kitchen",
  },
  {
    id: 30,
    title: "Borosil Glass Mixing Bowls",
    desc: "Set of 3 | Microwave Safe | Transparent",
    price: 699,
    originalPrice: 999,
    discount: "30% off",
    rating: 4.2,
    img: "https://rukminim2.flixcart.com/image/850/1000/xif0q/bowl/l/w/0/4-cect-gbowl-setof4-2100ml-withlid-cutting-edge-original-imah4kfu2kzq4nwd.jpeg?q=20&crop=false",
    category: "kitchen",
  },
  {
    id: 31,
    title: "Milton Thermosteel Lunch Box",
    desc: "3 Compartment | 1.2 Liter | Stainless Steel | Silver",
    price: 799,
    originalPrice: 1199,
    discount: "33% off",
    rating: 4.1,
    img: "https://m.media-amazon.com/images/I/51i16sIlF7L._AC_UF894,1000_QL80_.jpg",
    category: "kitchen",
  },
  {
    id: 32,
    title: "Prestige Tawa",
    desc: "Non-Stick | Induction Base | 27 cm | Black",
    price: 499,
    originalPrice: 799,
    discount: "38% off",
    rating: 4.0,
    img: "https://judge.ttkprestige.com/media/catalog/product/7/5/7524-37277-P-IMG1.jpg",
    category: "kitchen",
  },
  {
    id: 33,
    title: "Borosil Glass Water Bottle",
    desc: "1 Liter | Leak Proof | BPA Free | Transparent",
    price: 399,
    originalPrice: 599,
    discount: "33% off",
    rating: 4.2,
    img: "https://myborosil.com/cdn/shop/files/my-borosil-borosilicate-glass-bottles-750-ml-x-3-crysto-glass-bottle-set-of-3-blue-lid-32349054206090.jpg",
    category: "kitchen",
  },
  {
    id: 34,
    title: "Cello Plastic Water Jug",
    desc: "2 Liter | BPA Free | Transparent",
    price: 149,
    originalPrice: 249,
    discount: "40% off",
    rating: 3.8,
    img: "https://m.media-amazon.com/images/I/61Z3BEj+c9L._AC_UF350,350_QL80_.jpg",
    category: "kitchen",
  },
  {
    id: 35,
    title: "Nova Stainless Steel Spoon Set",
    desc: "Set of 6 | Mirror Finish | Silver",
    price: 299,
    originalPrice: 499,
    discount: "40% off",
    rating: 4.0,
    img: "https://m.media-amazon.com/images/I/81tXKPh4j2L._AC_UF350,350_QL80_.jpg",
    category: "kitchen",
  },
  {
    id: 36,
    title: "Wonderchef Kitchen Knife Set",
    desc: "Set of 3 | Stainless Steel | Black Handle",
    price: 899,
    originalPrice: 1299,
    discount: "31% off",
    rating: 4.3,
    img: "https://m.media-amazon.com/images/I/81VRmyhZKNS._AC_UF350,350_QL80_.jpg",
    category: "kitchen",
  },
  {
    id: 37,
    title: "Pigeon Kitchen Scissors",
    desc: "Stainless Steel | Multipurpose | Black",
    price: 199,
    originalPrice: 299,
    discount: "33% off",
    rating: 3.9,
    img: "https://m.media-amazon.com/images/I/81RQVwpmK7L._AC_UF350,350_QL80_.jpg",
    category: "kitchen",
  },
  {
    id: 38,
    title: "Borosil Glass Measuring Cup",
    desc: "500 ml | Microwave Safe | Transparent",
    price: 249,
    originalPrice: 399,
    discount: "38% off",
    rating: 4.1,
    img: "https://i5.walmartimages.com/asr/bebba757-2bc2-4588-a5d8-db9adc8d48a6.4ec35d10a101940a73a22aacf9df8f36.jpeg?odnHeight=768&odnWidth=768&odnBg=FFFFFF",
    category: "kitchen",
  },
  {
    id: 39,
    title: "Milton Thermosteel Sipper",
    desc: "600 ml | Stainless Steel | Vacuum Insulated | Silver",
    price: 599,
    originalPrice: 899,
    discount: "33% off",
    rating: 4.2,
    img: "https://cdn.zeptonow.com/production/ik-seo/tr:w-640,ar-1200-1200,pr-true,f-auto,q-80/cms/product_variant/46c82fea-fb0e-47d7-b4cd-f9cd2b6553ba/Milton-Flip-Lid-Thermosteel-Water-Bottle-1-L.jpeg",
    category: "kitchen",
  },
  {
    id: 40,
    title: "Prestige Spatula Set",
    desc: "Set of 3 | Silicone Head | Wooden Handle",
    price: 299,
    originalPrice: 499,
    discount: "40% off",
    rating: 4.0,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRaH42-3mlBJY9d8TfQG_ehohnkaFmLBdcRjw&s",
    category: "kitchen",
  },
  {
    id: 41,
    title: "Borosil Glass Storage Box",
    desc: "1 Liter | Airtight Lid | Microwave Safe | Transparent",
    price: 349,
    originalPrice: 499,
    discount: "30% off",
    rating: 4.1,
    img: "https://5.imimg.com/data5/SELLER/Default/2024/9/452728853/HU/ZO/FI/141467672/borosil-round-320-ml-lunch-box-set-of-3-500x500.jpg",
    category: "kitchen",
  },
  {
    id: 42,
    title: "Cello Plastic Storage Jars",
    desc: "Set of 3 | Airtight Lids | Assorted Colors",
    price: 499,
    originalPrice: 799,
    discount: "38% off",
    rating: 3.9,
    img: "https://m.media-amazon.com/images/I/71xJlektz3L._AC_UF894,1000_QL80_.jpg",
    category: "kitchen",
  },
  {
    id: 43,
    title: "Nova Stainless Steel Tongs",
    desc: "12 Inch | Silicone Tips | Silver",
    price: 199,
    originalPrice: 299,
    discount: "33% off",
    rating: 4.0,
    img: "https://m.media-amazon.com/images/I/716l-yNe7cL.jpg",
    category: "kitchen",
  },
  {
    id: 44,
    title: "Wonderchef Rolling Pin",
    desc: "Wooden | 14 Inch | Traditional Design",
    price: 249,
    originalPrice: 399,
    discount: "38% off",
    rating: 4.1,
    img: "https://rukminim2.flixcart.com/image/850/1000/kq18n0w0/kitchen-timer/z/3/6/ce01-canwood-original-imag44ws23k2b8pg.jpeg?q=90&crop=false",
    category: "kitchen",
  },
  {
    id: 45,
    title: "Pigeon Kitchen Scale",
    desc: "Digital | 5 kg Capacity | LCD Display | White",
    price: 599,
    originalPrice: 899,
    discount: "33% off",
    rating: 4.2,
    img: "https://assets.indiadesire.com/images/PigeonAmaze1800WattInductionCooktop_indiadesire.jpg",
    category: "kitchen",
  },
  {
    id: 46,
    title: "Borosil Glass Tea Cup",
    desc: "300 ml | Microwave Safe | Transparent",
    price: 149,
    originalPrice: 249,
    discount: "40% off",
    rating: 4.0,
    img: "https://www.zwende.com/cdn/shop/files/81_3ea601e6-3651-4aab-b410-d0fe65de72f5.jpg?v=1698763156&width=1080",
    category: "kitchen",
  },
  {
    id: 47,
    title: "Milton Thermosteel Coffee Mug",
    desc: "350 ml | Stainless Steel | Vacuum Insulated | Silver",
    price: 499,
    originalPrice: 799,
    discount: "38% off",
    rating: 4.3,
    img: "https://rukminim2.flixcart.com/image/850/1000/l4yi7bk0/mug/s/w/y/thermosteel-coffee-mug-300-ml-silver-hot-cold-flask-soup-flask-original-imagfqgegkpcnvuf.jpeg?q=90&crop=false",
    category: "kitchen",
  },
  {
    id: 48,
    title: "Prestige Kitchen Timer",
    desc: "Digital | Magnetic Back | Count Up/Down | Black",
    price: 299,
    originalPrice: 499,
    discount: "40% off",
    rating: 3.9,
    img: "https://images-eu.ssl-images-amazon.com/images/I/71xPmqaYvsL._AC_UL210_SR210,210_.jpg",
    category: "kitchen",
  },
  {
    id: 49,
    title: "Borosil Glass Baking Dish",
    desc: "2 Liter | Microwave Safe | Oven Safe | Transparent",
    price: 599,
    originalPrice: 899,
    discount: "33% off",
    rating: 4.1,
    img: "https://www.bigbasket.com/media/uploads/p/l/40239838_2-femora-borosilicate-glass-baking-dish-temperature-resistant-for-baking-serving-storing-use.jpg",
    category: "kitchen",
  },
  {
    id: 50,
    title: "Cello Plastic Chopping Board",
    desc: "Set of 2 | BPA Free | Non-Slip Base | Green & Red",
    price: 249,
    originalPrice: 399,
    discount: "38% off",
    rating: 4.0,
    img: "https://5.imimg.com/data5/JL/VL/HH/SELLER-4260965/pari-500x500.png",
    category: "kitchen",
  },
];

export default dataproducts;
